# Generated by Django 4.0.1 on 2022-02-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_materialtype_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='value',
        ),
    ]
