# Generated by Django 4.0.1 on 2022-02-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_quotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
