# Generated by Django 4.0.1 on 2022-02-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='document',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='phone',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='typematerial',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
